### PR TITLE
fix: xml2js is undefined

### PR DESCRIPTION
**Pull request by adityak74**
This is something I have been noticing for a while. Its a just a small variable name fix.

### CODE REVIEW

**Comment by rodrigograca31** [comment]
Seems good. will merge

**Comment by rodrigograca31** [comment]
@adityak74 thanks for contributing and making open source better!

**Comment by adityak74** [comment]
Thanks for merging @rodrigograca31. Will you push a new version for npm soon?

**Comment by rodrigograca31** [comment]
Oh..... forgot..... I kinda hate that nowadays we got to publish to "2 places"..... 

Will bump version and publish in a bit

**Comment by adityak74** [comment]
Thanks @rodrigograca31.

**Comment by rodrigograca31** [comment]
Done.

**Pull request merged**
