### PR TITLE
updated requireCordovaModule to require for non-cordova modules

### PR DESCRIPTION
**Pull request by mingxi**
Support cordova v9.0.0

### CODE REVIEW

**Comment by pklaes** [comment]
Changes worked for me with:
Corodva 9.0.0
Android 8.0.0
iOS 5.0.0
Windos 10 / Mac OS 10.14.4

**Comment by cvaliere** [comment]
yup, please merge it, it's very simple and without it, this plugin is not compatible with cordova 9

**Comment by cvaliere** [comment]
thanks :)

**Comment by rodrigograca31** [comment]
@mingxi Thanks for your contribution! :heart: 

@cvaliere and @pklaes thanks for letting me know it worked.

I'm still waiting for a reply a reply on #22 to merge it or not and then I will bump the plugin version, otherwise this change will take a bit to "spread" unless you guys use the `.git` url.............

**Comment by DaveLomber** [comment]
For older Cordova versions we started getting en error:

`Error: Cannot find module 'q'`

**Comment by rodrigograca31** [comment]
as I commented on the commit:

@DaveLomber hummmmmmmm, Yeah, seems it should.
We also have to add `path` and `glob` right?

Please `npm i q --save` and try to run the project and let us know if it complains about `path` and `glob` ?

@DaveLomber please answer here instead of in the commit.

**Comment by rodrigograca31** [comment]
@DaveLomber I tested it my self and already added `q`, `glob` and `path`
Please reinstall the plugin and everything should be good.

@stefansaenger no need to fork anymore.

**Comment by rodrigograca31** [comment]
and now I was reading the cordova 9.0.0 release notes and they dropped `Q` as a dependency ..... :joy: :joy: :joy: 
https://github.com/apache/cordova-lib/pull/710

If anyone wants to do the same for this plugin please go ahead!

**Comment by felvct** [comment]
Hey guys, what's the status on the dependency drop?

If no one looked into it, I may do it as soon as I got a little bit of time

**Comment by rodrigograca31** [comment]
@DaveLomber please check the latest code (from git) and let us know if everything works now!? 

PR #50 should solve your issue.

**Pull request merged**
