### PR TITLE
Removed q dependency

### PR DESCRIPTION
**Pull request by felvct**
Since cordova 9 dropped q as a dependency, I removed it from the project and refactored the q promises to native promise

### CODE REVIEW

**Comment by rodrigograca31** [comment]
Thanks for your contribution!

**Comment by rodrigograca31** [comment]
Will bump the version one of these days. Let's just see if no one complains about any bug.....

Just because I didnt have time to test it. Only reviewed the code and it looks good.

**Comment by felvct** [comment]
Yep, no worries.

I did build a project locally and the folder structure was as expected, I did not set up a full remote push test suite though.

Let's see how it goes 🙂

**Comment by rodrigograca31** [comment]
Just read the other thread where someone complained about `q` errors...... maybe I should bump the version already?

**Comment by felvct** [comment]
If this is a critical issue, you could bump it

Worst case: if something should really mess up, I could take a look on it later today

**Comment by rodrigograca31** [comment]
:+1:

**Comment by rodrigograca31** [comment]
Version bumped and published to npm!

**Pull request merged**
