### PR TITLE
Use different key per platform in json file

### PR DESCRIPTION
**Pull request by JanMisker**
A quick fix for my issue #37 was to change the .app key to .app_ios and .app_android. 
This way the android xml files are not 'contaminated' with the illegal keys often needed by iOS.

### CODE REVIEW

**Comment by rodrigograca31** [comment]
I'm inclined to not accept this PR... 
Thoughts? :thinking: :thought_balloon:

**Comment by pklaes** [comment]
I see the need for this, but as i understand with the proposed solution you would always have to maintain the .app translations twice, both for .app_ios and .app_android. It would be better to have three keys:
- .app for translations which a valid for both platforms
- .app_ios, .app_android specific for each platform as in this PR.

**Comment by rodrigograca31** [comment]
@pklaes exactly. I also saw the need but then we had to maintain two versions....
That's a good solution if someone wants to implement it. :)

**Comment by pklaes** [comment]
I'll have a look at it ...

**Comment by pklaes** [comment]
See #46

**Pull request closed without merging**
